// pages/tags/index.tsx
import Layout from '@/layouts/App';
import { Tag } from '@/types/article';
import Link from 'next/link';

import { getTagData } from '@/lib/tags';

export default function Tags() {
    const tags: Tag[] = getTagData();

    return (
        <Layout title='LEVEL-UP! - Tags'>
            <div className='flex w-3/5 m-auto space-x-8 divide-x-2'>
                <h1 className='text-6xl font-bold'>Tags</h1>
                <div className='flex flex-wrap max-w-lg pl-8 leading-10'>
                    {tags.map(tag => (
                        <span className='block uppercase font-lg'>
                            <Link
                                href='/tags/[id]'
                                as={`/tags/${tag.name}`}
                                className='pr-2 text-level-up-orange'
                            >
                                {tag.name}
                            </Link>
                            <span className='pr-6 text-level-up-grey-35'>
                                ({tag.count})
                            </span>
                        </span>
                    ))}
                </div>
            </div>
        </Layout>
    );
}

// src/routes/tags/+page.svelte
<script>
    import { getTagData } from "$lib/helpers/tags";

    $: tags = getTagData();
</script>

<div class="flex divide-x-2 space-x-8 w-3/5 m-auto">
    <h1 class="text-6xl font-bold">Tags</h1>
    <div class="flex flex-wrap max-w-lg pl-8 leading-10">
        {#each tags as tag}
        <span class="block uppercase font-lg">
            <a
                href="/tags/{tag.name}"
                class="text-level-up-orange pr-2"
            >{tag.name}</a>
            <span class="text-level-up-grey-35 pr-6">({tag.count})</span>
        </span>
        {/each}
    </div>
</div>
