// src/routes/tags/[tag]/+page.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import Article from '$lib/components/Article.svelte';
    import { getUniqueTags } from '$lib/helpers/tags';

    export let data;

    $: tag = $page.url.pathname.split("/").pop() || "";
</script>


<div class="divide-y-2 divide-level-up-grey-75">
    <h1 class="text-6xl font-bold pb-8">#{tag}</h1>
    
    <div>
        {#if !getUniqueTags().includes(tag)}
            <p class="text-xl py-4">
                No tags found that match "{tag}".
            </p>
        {/if}
        
        {#each data.articles as article}
            {#if article.tags.includes(tag)}
                <div class="py-4">
                    <Article data={article} />
                </div>
            {/if}
        {/each} 
    </div>
</div>

// pages/tags/[tag]/index.tsx
import Article from "@/components/article/Card";
import { articleData } from "@/data/articles";
import { Tag } from "@/types/article";
import { getUniqueTags } from "../load";

export default function TagPage() {
  const tags = getUniqueTags();
  const tag: Tag = {
    name: "tag",
    count: 4,
  };

  return (
    <div className="divide-y-2 divide-level-up-grey-75">
      <h1 className="pb-8 text-6xl font-bold">#{tag}</h1>

      <div>
        {tags.includes(tag.name) ? (
          <p className="py-4 text-xl">No tags found that match "{tag}".</p>
        ) : (
          articleData.map(
            (article) =>
              article.tags.includes(tag.name) && (
                <div className="py-4">
                  <Article {...article} />
                </div>
              )
          )
        )}
      </div>
    </div>
  );
}
